"""Writes src/theme/tokens.css from the game's own style sheets.

Every colour, opacity and size the site uses is read from the ink archive's database
(github.com/spuddeh/cp2077-ink-archive), so a value can be traced to the inkstyle it came from.
Run it again after the archive is rebuilt for a new game version.

    python scripts/ink-tokens.py [path/to/ink.db]
"""
import json
import re
import sqlite3
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_DB = HERE.parents[3] / "cp2077-ink-archive" / "data" / "ink.db"
OUT = HERE.parent / "src" / "theme" / "tokens.css"

# The game authors its UI at 3840x2160 and renders it at 1920x1080 at half size.
SCALE = 0.5

SHEETS = {
    "main": r"base\gameplay\gui\common\main_colors.inkstyle",
    "settings": r"base\gameplay\gui\fullscreen\settings\settings.inkstyle",
    "phone": r"base\gameplay\gui\widgets\phone\hud_phone_style.inkstyle",
}

SIZES = ["FluffFontSize", "ReadableXSmall", "ReadableSmall", "ReadableMedium", "ReadableFontSize",
         "SubtitleHeader", "TitleHeader"]
STATES = {"settings": ["Button", "Bool"], "phone": ["ContactListItem"]}


def kebab(name):
    name = name.replace("Fullscreen_", "Fs")
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", name).lower().replace("_", "-")


def hex_color(c):
    c = c.get("Value", c)
    if c.get("$type") == "Color":
        rgb = [c["Red"], c["Green"], c["Blue"]]
    else:
        rgb = [min(255, round(c[k] * 255)) for k in ("Red", "Green", "Blue")]
    return "#%02x%02x%02x" % tuple(rgb)


def props(db, path):
    row = db.execute("SELECT data FROM files WHERE path = ?", (path,)).fetchone()
    out = {}
    for style in json.loads(row[0])["styles"]:
        state = style.get("state", "Default")
        for p in style["properties"]:
            out[(state, p["propertyPath"])] = p["value"]
    return out


def css_value(value):
    inner = value.get("Value", value)
    if isinstance(inner, dict) and "referencedPath" in inner:
        return "var(--%s)" % kebab(inner["referencedPath"].split(".", 1)[1])
    if isinstance(inner, dict):
        return hex_color(inner)
    try:
        return str(round(float(inner), 3))
    except ValueError:
        return None


def main():
    db = sqlite3.connect(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DB)
    main_props = props(db, SHEETS["main"])
    lines = [
        "/* Generated by scripts/ink-tokens.py from the game's style sheets. Do not edit. */",
        ":root {",
        "  /* %s */" % SHEETS["main"],
    ]
    for (state, path), value in main_props.items():
        group, _, name = path.partition(".")
        if state == "Default" and group == "MainColors" and isinstance(value.get("Value"), dict)                 and "Red" in value["Value"]:
            lines.append("  --%s: %s;" % (kebab(name), hex_color(value)))
    for name in SIZES:
        px = float(main_props[("Default", "MainColors." + name)]["Value"]) * SCALE
        lines.append("  --font-%s: %gpx;" % (kebab(name), px))
    for sheet, prefixes in STATES.items():
        sheet_props = props(db, SHEETS[sheet])
        lines.append("")
        lines.append("  /* %s */" % SHEETS[sheet])
        for (state, path), value in sorted(sheet_props.items(), key=lambda kv: (kv[0][1], kv[0][0])):
            group, _, field = path.partition(".")
            if group not in prefixes:
                continue
            css = css_value(value)
            if css is not None:
                lines.append("  --%s-%s-%s: %s;" % (kebab(group), kebab(field), state.lower(), css))
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", OUT, len(lines), "lines")


if __name__ == "__main__":
    main()
